/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdf93",
        "on-tertiary-fixed-variant": "#594400",
        tertiary: "#765b00",
        "surface-tint": "#6750a4",
        "surface-container-high": "#ece6ee",
        "on-tertiary-fixed": "#241a00",
        "primary-container": "#6750a4",
        "on-primary-container": "#e0d2ff",
        "on-secondary-fixed": "#1f1635",
        outline: "#7a7582",
        "secondary-fixed": "#e9ddff",
        "inverse-surface": "#322f35",
        "surface-dim": "#ded8e0",
        "primary-fixed-dim": "#cfbcff",
        "on-tertiary-container": "#503d00",
        "on-surface-variant": "#494551",
        "on-primary-fixed": "#22005d",
        "on-background": "#1d1b20",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container": "#f2ecf4",
        "surface-container-low": "#f8f2fa",
        "on-secondary-container": "#645a7d",
        "on-secondary": "#ffffff",
        "surface-variant": "#e6e0e9",
        "on-secondary-fixed-variant": "#4b4263",
        "secondary-fixed-dim": "#cdc0e9",
        primary: "#4f378a",
        "surface-container-lowest": "#ffffff",
        secondary: "#63597c",
        "inverse-primary": "#cfbcff",
        "surface-container-highest": "#e6e0e9",
        "on-primary-fixed-variant": "#4f378a",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        background: "#faf7ff",
        "outline-variant": "#cbc4d2",
        "on-surface": "#1d1b20",
        "primary-fixed": "#e9ddff",
        surface: "#fdf7ff",
        "inverse-on-surface": "#f5eff7",
        "secondary-container": "#e1d4fd",
        "tertiary-fixed-dim": "#e7c365",
        "tertiary-container": "#c9a74d",
        "surface-bright": "#fdf7ff",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        // Extra accents
        "primary-light": "#7c5fc4",
        "primary-dark": "#3a2470",
        "accent-violet": "#9c6fde",
        "accent-indigo": "#6366f1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.375rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "5xl": "2.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        headline: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        body: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        label: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
      },
      boxShadow: {
        card: "0 2px 12px 0 rgba(79,55,138,0.06), 0 1px 3px 0 rgba(0,0,0,0.06)",
        "card-hover": "0 8px 30px 0 rgba(79,55,138,0.12), 0 2px 8px 0 rgba(0,0,0,0.06)",
        elevated: "0 4px 24px 0 rgba(79,55,138,0.10), 0 1px 4px 0 rgba(0,0,0,0.05)",
        glow: "0 0 0 4px rgba(79,55,138,0.15), 0 8px 32px rgba(79,55,138,0.2)",
        "glow-sm": "0 0 0 3px rgba(79,55,138,0.12), 0 4px 16px rgba(79,55,138,0.15)",
        "inner-soft": "inset 0 1px 4px rgba(0,0,0,0.06)",
        "sidebar": "4px 0 24px rgba(79,55,138,0.08)",
        "modal": "0 24px 80px rgba(0,0,0,0.18), 0 4px 16px rgba(0,0,0,0.08)",
      },
      animation: {
        "fade-up": "fadeSlideUp 0.4s cubic-bezier(0.16,1,0.3,1) both",
        "fade-in": "fadeIn 0.3s ease both",
        "scale-in": "scaleIn 0.25s cubic-bezier(0.34,1.56,0.64,1) both",
        "glow-pulse": "glowPulse 2.5s ease-in-out infinite",
        "slide-in-left": "slideInLeft 0.35s cubic-bezier(0.16,1,0.3,1) both",
        "shimmer": "shimmer 1.8s linear infinite",
        "float": "float 3s ease-in-out infinite",
      },
      keyframes: {
        fadeSlideUp: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.92)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        glowPulse: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(79,55,138,0.2)" },
          "50%": { boxShadow: "0 0 0 8px rgba(79,55,138,0)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% center" },
          "100%": { backgroundPosition: "200% center" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, #3a2470 0%, #4f378a 45%, #7c5fc4 100%)",
        "gradient-card": "linear-gradient(135deg, #6750a4 0%, #9c6fde 100%)",
        "gradient-warm": "linear-gradient(135deg, #f8f2fa 0%, #ede7f6 100%)",
        "gradient-mesh": "radial-gradient(at 40% 20%, #ede7f6 0, transparent 50%), radial-gradient(at 80% 0%, #e8def8 0, transparent 50%), radial-gradient(at 0% 50%, #f3e5f5 0, transparent 50%)",
      },
    },
  },
  plugins: [],
};
